config/routes.rb
Rails.application.routes.draw do
  resources :animals

  root to: 'animals#index'
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:name, :age)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<div data-controller="animal-form">
  <%= form_with(model: animal) do |form| %>
    <% if animal.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

        <ul>
          <% animal.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, "data-target" => "animal-form.name", "data-action" => "keyup->animal-form#countCharacters"  %>
      Characters: <span data-target="animal-form.counter"><%= "animal-form.name.to_s.size" %></span>
    </div>

    <div class="field">
      <%= form.label :age %>
      <%= form.number_field :age %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= animal.age %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @animal.age %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusDemoPetsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>